---
- name: >
    Installs PHP, WP-CLI, MariaDB, WordPress, PHP-FPM, Nginx, Apache2, HHVM,
    Redis. Disables the software from starting on boot and stops them.
    Run other playbooks to set up the server for serving.

  hosts: webservers
  remote_user: root

  roles:
    - common
    - php
    - wp-cli
    - mysql
    - wordpress-install
    - php-fpm
    - nginx
    - apache
    - iptables
    - hhvm
    - redis
    - monit
    
