---
- name: Install MySQL
  apt: name={{ item }} state=latest update_cache=true
  with_items:
    - python-mysqldb
    - mysql-server
    - mysql-client
    - libmysqlclient-dev

- name: Ensure MySQL service is up
  action: service name=mysql state=started

- name: Copy .my.cnf file with root password credentials
  template: src=templates/my.cnf dest=/root/.my.cnf owner=root mode=0600

- name: Update MySQL root password for all root accounts
  action: mysql_user name=root password={{ mysql_root_password  }} host_all=yes

- name: Ensure anonymous users are not in the database
  action: mysql_user name='' host={{ item }} state=absent
  with_inventory_hostnames: db


- name: Create MySQL Database
  action: mysql_db name={{ item.wordpress_db_name  }} state=present encoding=utf8mb4
  with_items: '{{ sites_to_set_up }}'

- name: Create MySQL User
  action: mysql_user name={{ item.wordpress_db_user  }} priv={{ item.wordpress_db_user  }}.*:ALL state=present password="{{ item.wordpress_db_user_pass }}"
  with_items: '{{ sites_to_set_up }}'
