---

- name: Drop WordPress database
  mysql_db: name="{{ item.wordpress_db_name }}"
            state=absent
            login_user=root
            login_password="{{ mysql_root_password }}"
  with_items: '{{ sites_to_set_up }}'

- name: Drop WordPress DB user
  mysql_user: name="{{ item.wordpress_db_user }}"
              state=absent
              login_user="root"
              login_password="{{ mysql_root_password }}"
  with_items: '{{ sites_to_set_up }}'

- name: Remove WordPress directory
  file: path="{{ remote_wordpress_dir }}"
        state=absent
